kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: edge
  name: edge
  namespace: srs-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: edge
  template:
    metadata:
      labels:
        app: edge
    spec:
      volumes:
        - name: conf
          configMap:
            name: edge-conf
      containers:
      - name: srs
        image: 'hub.bigdatagz.com/ossrs/srs:v4.0'
        imagePullPolicy: Always
        ports:
          - name: rtmp
            containerPort: 1935
        volumeMounts:
          - name: conf
            mountPath: /app
        livenessProbe: 
          httpGet:
            path: /api/v1/versions
            port: 1985
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: sidecar
        image: 'hub.bigdatagz.com/ossrs/node-srs-sidecar:v1.0'
        imagePullPolicy: Always
        ports:
          - name: sidecar
            containerPort: 3000
        envFrom:
          - configMapRef:
              name: sidecar-env
      - name: configmap-reload
        image: 'hub.bigdatagz.com/jimmidyson/configmap-reload:v0.3.0'
        volumeMounts:
          - name: conf
            mountPath: /app
        args:
          - '-volume-dir'
          - '/app'
          - '-webhook-url'
          - 'http://127.0.0.1:1985/api/v1/raw?rpc=reload&scope=configmap&data=/app/srs.conf'
      restartPolicy: Always
  strategy:
    type: RollingUpdate