apiVersion: v1
kind: ConfigMap
metadata:
  name: hls-fragment-conf
  namespace: srs-cluster
data:
  srs.conf: |-
    listen             1935;
    max_connections    6000;
    daemon             off;
    srs_log_tank       console;
    srs_log_level      warn;
    pid                ./objs/srs.pid;
    http_api {
      enabled          on;
      listen           1985;
      raw_api {
        enabled        on;
        allow_reload   on;
      }
    }
    vhost __defaultVhost__ {
      http_hooks {
        enabled        on;
        on_hls         http://127.0.0.1:3000/storage;
      }
      hls {
        enabled        on;
        hls_path       ./objs/nginx/html;
        hls_fragment   10;
        hls_window     60;
      }
    }
