kind: Service
apiVersion: v1
metadata:
  name: hls-fragment-svc
  namespace: srs-cluster
spec:
  clusterIP: None
  ports:
    - name: rtmp
      port: 1935
      targetPort: rtmp
  selector:
    app: hls-fragment