kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: hls-fragment
  name: hls-fragment
  namespace: srs-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hls-fragment
  template:
    metadata:
      labels:
        app: hls-fragment
    spec:
      volumes:
        - name: conf
          configMap:
            name: hls-fragment-conf
        - name: hls
          emptyDir: {}
      containers:
      - name: srs
        image: 'hub.bigdatagz.com/ossrs/srs:v4.0'
        imagePullPolicy: Always
        ports:
          - name: rtmp
            containerPort: 1935
        volumeMounts:
          - name: conf
            mountPath: /app
          - name: hls
            mountPath: /usr/local/srs/objs/nginx/html
        livenessProbe: 
          httpGet:
            path: /api/v1/versions
            port: 1985
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: sidecar
        image: 'hub.bigdatagz.com/ossrs/node-srs-sidecar:v1.0'
        imagePullPolicy: Always
        ports:
          - name: sidecar
            containerPort: 3000
        envFrom:
          - configMapRef:
              name: sidecar-env
        volumeMounts:
          - name: hls
            mountPath: /app/public
        args:
          - webhook
      restartPolicy: Always
      hostAliases:
        - ip: 10.204.62.33
          hostnames:
            - pan.bigdatagz.com
