kind: Service
apiVersion: v1
metadata:
  name: origin-svc
  namespace: srs-cluster
  labels:
    app: origin
spec:
  ports:
    - name: rtmp
      port: 1935
      targetPort: rtmp
  selector:
    app: origin