apiVersion: v1
kind: ConfigMap
metadata:
  name: origin-conf
  namespace: srs-cluster
data:
  srs.conf: |-
    listen             1935;
    max_connections    6000;
    daemon             off;
    srs_log_tank       console;
    pid                ./objs/srs.pid;
    http_api {
      enabled          on;
      listen           1985;
      raw_api {
        enabled        on;
        allow_reload   on;
      }
    }
    vhost __defaultVhost__ {
      cluster {
        mode           local;
        origin_cluster on;
        coworkers      127.0.0.1:3000;
      }
      http_hooks {
        enabled        on;
        on_publish     http://127.0.0.1:3000/auth/publish;
        on_play        http://127.0.0.1:3000/auth/play;
        on_hls         http://127.0.0.1:3000/storage;
      }
      hls {
        enabled        on;
        hls_path       ./objs/nginx/html;
        hls_fragment   10;
        hls_window     60;
      }
    }
