kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: proxy
  name: proxy
  namespace: srs-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      volumes:
        - name: conf
          configMap:
            name: proxy-conf
        - name: hls
          emptyDir: {}
      containers:
      - name: srs
        image: 'hub.bigdatagz.com/ossrs/srs:v4.0'
        imagePullPolicy: Always
        ports:
          - name: rtmp
            containerPort: 1935
        volumeMounts:
          - name: conf
            mountPath: /app
        livenessProbe: 
          httpGet:
            path: /api/v1/versions
            port: 1985
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: sidecar
        image: 'hub.bigdatagz.com/ossrs/node-srs-sidecar:v1.0'
        imagePullPolicy: Always
        ports:
          - name: sidecar
            containerPort: 3000
        env:
          - name: UPSTREAM_URL
            value: http://edge-svc.srs-cluster.svc.prod.dict.gz.cmcc:3000
        volumeMounts:
          - name: hls
            mountPath: /app/public
        args:
          - proxy
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1